/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    industries: Industry;
    infrastructure: Infrastructure;
    workloads: Workload;
    applications: Application;
    'case-studies': CaseStudy;
    posts: Post;
    authors: Author;
    faqs: Faq;
    testimonials: Testimonial;
    partners: Partner;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    infrastructure: InfrastructureSelect<false> | InfrastructureSelect<true>;
    workloads: WorkloadsSelect<false> | WorkloadsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'cta-blocks': CtaBlock;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'cta-blocks': CtaBlocksSelect<false> | CtaBlocksSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor' | 'sales') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  /**
   * Auto-generated from the title/name. Edit to override.
   */
  slug?: string | null;
  tagline?: string | null;
  heroImage?: (number | null) | Media;
  heroCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  challenges?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  workloads?: (number | Workload)[] | null;
  featuredApplications?: (number | Application)[] | null;
  /**
   * Explain why this industry needs what it needs. Structured per-workload requirements come from each linked Workload's requirement profile.
   */
  requirementsNarrative?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  recommendedInfrastructure?: (number | Infrastructure)[] | null;
  possibleArchitecture?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    diagram?: (number | null) | Media;
  };
  caseStudies?: (number | CaseStudy)[] | null;
  faqs?: (number | Faq)[] | null;
  seo?: {
    /**
     * Overrides the default <title>. ~60 characters.
     */
    title?: string | null;
    /**
     * Meta description. ~155 characters.
     */
    description?: string | null;
    /**
     * Social share image (1200x630).
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * The hub of the content graph: Industry -> Workload -> Application -> Requirement -> Infrastructure.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workloads".
 */
export interface Workload {
  id: number;
  name: string;
  /**
   * Auto-generated from the title/name. Edit to override.
   */
  slug?: string | null;
  description?: string | null;
  applications?: (number | Application)[] | null;
  requirementProfile?: {
    cpuIntensity?: ('low' | 'medium' | 'high' | 'extreme') | null;
    gpuIntensity?: ('none' | 'low' | 'medium' | 'high' | 'extreme') | null;
    /**
     * Minimum VRAM per GPU, in GB.
     */
    vramMinGB?: number | null;
    /**
     * Minimum system RAM, in GB.
     */
    ramMinGB?: number | null;
    storageType?: ('hdd' | 'sata-ssd' | 'nvme-ssd' | 'nvme-raid' | 'parallel-fs') | null;
    /**
     * e.g. "3+ GB/s sustained read"
     */
    storageThroughput?: string | null;
    networkMin?: ('1gbe' | '10gbe' | '25gbe' | '100gbe' | 'infiniband') | null;
    scalingPattern?: ('single-workstation' | 'scale-up' | 'scale-out-cluster' | 'hybrid-cloud-burst') | null;
  };
  recommendedInfrastructure?: (number | Infrastructure)[] | null;
  /**
   * Industries where this workload commonly appears.
   */
  industries?: (number | Industry)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  name: string;
  /**
   * Auto-generated from the title/name. Edit to override.
   */
  slug?: string | null;
  vendor?: string | null;
  category?:
    | (
        | '3d-rendering'
        | 'simulation'
        | 'compositing-vfx'
        | 'cad-bim'
        | 'ai-ml'
        | 'trading-quant'
        | 'media-editing'
        | 'other'
      )
    | null;
  logo?: (number | null) | Media;
  workloads?: (number | Workload)[] | null;
  /**
   * What this application is bottlenecked by, e.g. "Redshift is VRAM-bound and scales near-linearly across GPUs."
   */
  optimisationNotes?: string | null;
  /**
   * Infrastructure this application is certified/optimized for.
   */
  certifiedHardware?: (number | Infrastructure)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Infrastructure categories and products, e.g. Compute > GPU Servers. Keep URLs flat; use `parent` for the mega-menu hierarchy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infrastructure".
 */
export interface Infrastructure {
  id: number;
  name: string;
  /**
   * Auto-generated from the title/name. Edit to override.
   */
  slug?: string | null;
  category: 'compute' | 'storage' | 'networking' | 'data-protection';
  /**
   * Optional. Set for sub-items, e.g. GPU Servers' parent is the Compute category entry.
   */
  parent?: (number | null) | Infrastructure;
  /**
   * Short card/teaser copy (~160 chars).
   */
  summary?: string | null;
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  useCases?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  capabilities?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  businessValue?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  suitedWorkloads?: (number | Workload)[] | null;
  relatedIndustries?: (number | Industry)[] | null;
  heroImage?: (number | null) | Media;
  seo?: {
    /**
     * Overrides the default <title>. ~60 characters.
     */
    title?: string | null;
    /**
     * Meta description. ~155 characters.
     */
    description?: string | null;
    /**
     * Social share image (1200x630).
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * Auto-generated from the title/name. Edit to override.
   */
  slug?: string | null;
  clientName?: string | null;
  /**
   * Show as "A [City]-based [industry] studio" instead of the client name.
   */
  clientAnonymous?: boolean | null;
  industry?: (number | null) | Industry;
  coverImage?: (number | null) | Media;
  summary?: string | null;
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  approach?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  infrastructureDeployed?: (number | Infrastructure)[] | null;
  results?:
    | {
        metric: string;
        before?: string | null;
        after?: string | null;
        id?: string | null;
      }[]
    | null;
  quote?: {
    text?: string | null;
    person?: string | null;
    role?: string | null;
  };
  publishedAt?: string | null;
  seo?: {
    /**
     * Overrides the default <title>. ~60 characters.
     */
    title?: string | null;
    /**
     * Meta description. ~155 characters.
     */
    description?: string | null;
    /**
     * Social share image (1200x630).
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  scope?: ('global' | 'industry' | 'infrastructure') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-generated from the title/name. Edit to override.
   */
  slug?: string | null;
  type: 'blog' | 'insight';
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | Author;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  relatedIndustries?: (number | Industry)[] | null;
  relatedInfrastructure?: (number | Infrastructure)[] | null;
  publishedAt?: string | null;
  seo?: {
    /**
     * Overrides the default <title>. ~60 characters.
     */
    title?: string | null;
    /**
     * Meta description. ~155 characters.
     */
    description?: string | null;
    /**
     * Social share image (1200x630).
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  role?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  linkedin?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  person: string;
  role?: string | null;
  company?: string | null;
  logo?: (number | null) | Media;
  industry?: (number | null) | Industry;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo: number | Media;
  tier?: ('oem' | 'partner' | 'distributor') | null;
  /**
   * Which infrastructure categories this partner is relevant to.
   */
  categories?: (number | Infrastructure)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  company: string;
  email: string;
  phone?: string | null;
  industry?: (number | null) | Industry;
  interestedInfrastructure?: (number | Infrastructure)[] | null;
  workloadDescription?: string | null;
  applicationsUsed?: string | null;
  companySize?: ('1-10' | '11-50' | '51-200' | '201-500' | '500+') | null;
  message?: string | null;
  source?: {
    sourceUrl?: string | null;
    referrer?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
  };
  status?: ('new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost') | null;
  assignedTo?: (number | null) | User;
  internalNotes?:
    | {
        note: string;
        author?: (number | null) | User;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'infrastructure';
        value: number | Infrastructure;
      } | null)
    | ({
        relationTo: 'workloads';
        value: number | Workload;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  heroImage?: T;
  heroCopy?: T;
  challenges?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  workloads?: T;
  featuredApplications?: T;
  requirementsNarrative?: T;
  recommendedInfrastructure?: T;
  possibleArchitecture?:
    | T
    | {
        description?: T;
        diagram?: T;
      };
  caseStudies?: T;
  faqs?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infrastructure_select".
 */
export interface InfrastructureSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  parent?: T;
  summary?: T;
  overview?: T;
  useCases?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  capabilities?:
    | T
    | {
        text?: T;
        id?: T;
      };
  businessValue?:
    | T
    | {
        text?: T;
        id?: T;
      };
  suitedWorkloads?: T;
  relatedIndustries?: T;
  heroImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workloads_select".
 */
export interface WorkloadsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  applications?: T;
  requirementProfile?:
    | T
    | {
        cpuIntensity?: T;
        gpuIntensity?: T;
        vramMinGB?: T;
        ramMinGB?: T;
        storageType?: T;
        storageThroughput?: T;
        networkMin?: T;
        scalingPattern?: T;
      };
  recommendedInfrastructure?: T;
  industries?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  vendor?: T;
  category?: T;
  logo?: T;
  workloads?: T;
  optimisationNotes?: T;
  certifiedHardware?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  clientName?: T;
  clientAnonymous?: T;
  industry?: T;
  coverImage?: T;
  summary?: T;
  challenge?: T;
  approach?: T;
  infrastructureDeployed?: T;
  results?:
    | T
    | {
        metric?: T;
        before?: T;
        after?: T;
        id?: T;
      };
  quote?:
    | T
    | {
        text?: T;
        person?: T;
        role?: T;
      };
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedIndustries?: T;
  relatedInfrastructure?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  linkedin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  scope?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  person?: T;
  role?: T;
  company?: T;
  logo?: T;
  industry?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  tier?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  email?: T;
  phone?: T;
  industry?: T;
  interestedInfrastructure?: T;
  workloadDescription?: T;
  applicationsUsed?: T;
  companySize?: T;
  message?: T;
  source?:
    | T
    | {
        sourceUrl?: T;
        referrer?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
      };
  status?: T;
  assignedTo?: T;
  internalNotes?:
    | T
    | {
        note?: T;
        author?: T;
        date?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  social?:
    | {
        platform?: ('linkedin' | 'twitter' | 'youtube' | 'instagram') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Industries and Infrastructure mega-menus are generated live from those collections, so a new industry or product shows up in the nav automatically. Use this global for the footer and any extra top-level links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. copyright / CIN / registered office line.
   */
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Reusable CTA copy so messaging can be edited in one place instead of on every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-blocks".
 */
export interface CtaBlock {
  id: number;
  blocks?:
    | {
        /**
         * e.g. "final-cta", "industry-cta", "infrastructure-cta"
         */
        key: string;
        heading: string;
        subtext?: string | null;
        primaryLabel?: string | null;
        primaryHref?: string | null;
        secondaryLabel?: string | null;
        secondaryHref?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  logoDark?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-blocks_select".
 */
export interface CtaBlocksSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        key?: T;
        heading?: T;
        subtext?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}